version: '3.5'

services:
  postgres:
    container_name: openai_feishu_db
    image: postgres:latest
    environment:
      POSTGRES_USER: openai_feishu
      POSTGRES_DB: openai_feishu
      POSTGRES_PASSWORD: OpenAI_Feishu
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"


volumes:
  postgres-db:
    driver: local
